{% set version = "7.1.1" %}
# {% set version = "8.1.1" %}
{% set build_number = 0 %}

{% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 2d5cdd048540144d821715c718932591418bb48f5b6bb19becdae62339efa75a
  # sha256: 71a09b4340f0a9c58559fe946dc745ab68a866cf20636a41d97b6046cb736324

build:
  number: {{ build_number }}

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    # - python
    # VTK Third Party dependencies
    - zlib
    - freetype
    - hdf5
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    - tbb
    - tbb-devel
    # - libnetcdf
    # - lz4-c
  run:
    # - python
    # - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib
    - freetype
    - hdf5
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    - tbb
    # - libnetcdf
    # - lz4-c

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - v-turin
